2025-06-13 10:18:31,344 [INFO] Iniciando aplicación OBD2 Scanner...
2025-06-13 10:18:32,206 [DEBUG] Using selector: _Selector
2025-06-13 10:18:32,679 [CRITICAL] Excepción no capturada:
Traceback (most recent call last):
  File "/Users/ignacioeltit/git/proyecto01junio/ob2_nuevo7junio/scanner-obd2/src/main.py", line 539, in <module>
    win = DataVisualizer(lambda: {}, pid_manager=None, elm327=None, parse_pid_response=None, backend=backend)
  File "/Users/ignacioeltit/git/proyecto01junio/ob2_nuevo7junio/scanner-obd2/src/ui/data_visualizer.py", line 111, in __init__
    self.init_ui()  # <-- Primero inicializa la UI (crea self.tabs)
  File "/Users/ignacioeltit/git/proyecto01junio/ob2_nuevo7junio/scanner-obd2/src/ui/data_visualizer.py", line 239, in init_ui
    self.graphs_layout.addWidget(self.graph_plot)
TypeError: 'PySide6.QtWidgets.QBoxLayout.addWidget' called with wrong argument types:
  PySide6.QtWidgets.QBoxLayout.addWidget(PlotWidget)
Supported signatures:
  PySide6.QtWidgets.QBoxLayout.addWidget(arg__1: PySide6.QtWidgets.QWidget, /, stretch: Optional[int] = None, alignment: PySide6.QtCore.Qt.AlignmentFlag = Default(Qt.Alignment))
